# Generated by Django 2.2 on 2022-04-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220413_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
